# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wps.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(651, 468)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(250, 350, 101, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.refresh)

        self.pushButton_1 = QtWidgets.QPushButton(Form)
        self.pushButton_1.setGeometry(QtCore.QRect(250, 410, 101, 41))
        self.pushButton_1.setObjectName("out_Button")
        self.pushButton_1.clicked.connect(self.refresh)

        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(240, 70, 151, 31))
        self.lineEdit.setObjectName("loaction")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(160, 80, 54, 12))
        self.label.setObjectName("label")

        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(240, 140, 111, 31))
        self.lineEdit_2.setObjectName("prefix")

        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(150, 150, 54, 12))
        self.label_2.setObjectName("label_2")

        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(240, 190, 111, 31))
        self.lineEdit_3.setObjectName("Draw_num")

        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(160, 210, 54, 12))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")

        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(160, 200, 54, 12))
        self.label_4.setObjectName("label_4")

        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(240, 250, 111, 31))
        self.lineEdit_4.setObjectName("suffix")

        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(150, 260, 54, 16))
        self.label_5.setObjectName("label_5")

        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(370, 200, 54, 12))
        self.label_6.setObjectName("label_6")

        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(370, 260, 54, 12))
        self.label_8.setObjectName("label_8")

        self.lineEdit_5 = QtWidgets.QTextEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(240, 310, 111, 31))
        self.lineEdit_5.setObjectName("output")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Update_xls"))
        self.pushButton.setText(_translate("Form", "一键更新"))
        self.pushButton_1.setText(_translate("Form", "一键导出"))
        self.label.setText(_translate("Form", "表格位置"))
        self.label_2.setText(_translate("Form", "内容前缀"))
        self.label_4.setText(_translate("Form", "图号"))
        self.label_5.setText(_translate("Form", "更新后缀"))
        self.label_6.setText(_translate("Form", "1,2,3,4"))
        self.label_8.setText(_translate("Form", "1,2,3,4"))

    def refresh(self):
        val = self.lineEdit.text()
        print(val)
